# Generated by Django 4.1.6 on 2023-02-09 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_degree_semester_alter_user_image_speciality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Cours', 'Cours'), ('Tp', 'Tp'), ('Td', 'Td'), ('Extra', 'Extra')], default='Cours', max_length=255, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='document',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Speciality',
        ),
        migrations.RemoveField(
            model_name='course',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='user',
            name='degrees',
        ),
        migrations.AddField(
            model_name='course',
            name='Specialitys',
            field=models.ManyToManyField(blank=True, to='core.speciality'),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, to='core.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='document',
            name='documenttype',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.documenttype'),
        ),
    ]
