# Generated by Django 4.1.6 on 2023-02-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_documenttype_rename_user_document_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.SlugField(max_length=255),
        ),
    ]
