# Generated by Django 4.1.6 on 2023-02-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_planningexams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanningExams',
            new_name='PlanningExam',
        ),
    ]
