# Generated by Django 4.1.6 on 2023-02-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_planningexams_planningexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningexam',
            name='document',
            field=models.ImageField(upload_to='documents/planningexams/'),
        ),
    ]
