# Generated by Django 4.1.6 on 2023-02-12 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_degree_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.CharField(choices=[('l2', 'Licence 2'), ('l3', 'Licence 3'), ('m1', 'Master 1'), ('m2', 'Master 2')], default='l2', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='planningexam',
            name='Speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.speciality', unique=True),
        ),
    ]
