# Generated by Django 4.1.6 on 2023-02-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_speciality_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planningexam',
            unique_together={('Speciality',)},
        ),
    ]
