# Generated by Django 4.1.7 on 2023-04-01 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_planningexam_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='images/defaultprofile.png', null=True, upload_to='images'),
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(upload_to='images')),
                ('Speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.speciality')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.degree')),
            ],
            options={
                'unique_together': {('Speciality',)},
            },
        ),
    ]
