# Generated by Django 4.1.7 on 2023-04-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_user_image_planning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speciality",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
